### ISSUE TITLE
cannot load such file -- statistics (LoadError)

### ISSUE THREAD

**Issue by eddygarcas** [estebanz01/ruby-statistics#145]
Hi, hope you can help me,
I'm getting this error locally running my server using:
```
Ruby 3.3.4
Rails 7.1.2
```

```
09:49:31 web.1    | /home/duard/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- statistics (LoadError)
09:49:31 web.1    | Did you mean?  ruby-statistics
09:49:31 web.1    | 	from /home/duard/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
09:49:31 web.1    | 	from /home/duard/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
09:49:31 web.1    | 	from /home/duard/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
09:49:31 web.1    | 	from /home/duard/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/derailed_benchmarks-2.1.2/lib/derailed_benchmarks/stats_from_dir.rb:4:in `<main>'
09:49:31 web.1    | 	from /home/duard/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
```

**Comment by eddygarcas** [comment]
Apologies, closing this as there is a issue open in derailed_benchmarks
[https://github.com/zombocom/derailed_benchmarks/issues/237](https://github.com/zombocom/derailed_benchmarks/issues/237)
